scarab:
  env_file: .env
  restart: always
  links:
    - django
django:
  build: .
  env_file: .env
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  volumes:
    - .:/usr/src/app

# By default, django just uses sqlite. To add a database, you'd add this `links` hash to the `django` app above,
# and add a new app called mysql (or whatever your db is), like the one below.
# Once added, the host and port for mysql would be available in the environment as:
# MYSQL_1_PORT_8000_TCP_ADDR + ':' + MYSQL_1_PORT_8000_TCP_PORT
  # links:
  #   - mysql
# mysql:
#   image: mysql
#   env_file: .env
#   ports:
#     - "3306:3306"
